GET http://localhost:5176/
###
GET http://localhost:5176/blog
###
GET http://localhost:5176/blog/4
###
POST http://localhost:5176/blog
Content-Type: application/json

{
    "title" : "This is my Third Blog",
    "body" : "This is my Third post"
}
###
DELETE http://localhost:5176/blog/1
###
PUT http://localhost:5176/blog/0
Content-Type: application/json

{
    "title" : "This is my Changed Blog",
    "body" : "This is my Changed post"
}

### Middleware check

POST http://localhost:5176/blog/api
Content-Type: application/json
X-Api-Key: thisIsBadPassword

{
    "title" : "This is my Changed Blog",
    "body" : "This is my Changed post"
}